#!/usr/bin/env python3
"""PostToolUse: scan edited files for TODO/FIXME/HACK comments and log them."""
import json
import re
import subprocess
import sys
from pathlib import Path

TODO_PATTERN = re.compile(r"#\s*(TODO|FIXME|HACK|XXX)[\s:：](.+)", re.IGNORECASE)

try:
    root = subprocess.check_output(
        ["git", "rev-parse", "--show-toplevel"], text=True, stderr=subprocess.DEVNULL
    ).strip()
except subprocess.CalledProcessError:
    root = "."

TODO_FILE = Path(root) / "docs" / "agent-todos.md"
TODO_FILE.parent.mkdir(parents=True, exist_ok=True)

try:
    data = json.loads(sys.stdin.read())
except json.JSONDecodeError:
    print("{}")
    sys.exit(0)

tool = data.get("tool_name", "")
file_path = data.get("tool_input", {}).get("file_path", "")

if tool not in ("Edit", "Write") or not file_path:
    print("{}")
    sys.exit(0)

# Only scan source files
if not any(file_path.endswith(ext) for ext in (".py", ".ts", ".tsx", ".js", ".jsx", ".java", ".rs", ".go")):
    print("{}")
    sys.exit(0)

full_path = Path(root) / file_path if not Path(file_path).is_absolute() else Path(file_path)
if not full_path.exists():
    print("{}")
    sys.exit(0)

try:
    lines = full_path.read_text(encoding="utf-8", errors="replace").splitlines()
except OSError:
    print("{}")
    sys.exit(0)

found = []
for i, line in enumerate(lines, 1):
    m = TODO_PATTERN.search(line)
    if m:
        tag = m.group(1).upper()
        text = m.group(2).strip()
        found.append((file_path, i, tag, text))

if not found:
    print("{}")
    sys.exit(0)

# Read existing TODOs to avoid duplicates
existing = set()
if TODO_FILE.exists():
    for line in TODO_FILE.read_text(encoding="utf-8").splitlines():
        existing.add(line.strip())

# Append new TODOs
new_entries = []
for fpath, lineno, tag, text in found:
    entry = f"- [{tag}] `{fpath}:{lineno}` {text}"
    if entry not in existing:
        new_entries.append(entry)

if new_entries:
    with TODO_FILE.open("a", encoding="utf-8") as f:
        if TODO_FILE.stat().st_size == 0:
            f.write("# Agent TODO Tracker\n\n")
            f.write("Auto-generated by `track-todos.py` hook. Each entry maps a TODO/FIXME/HACK comment to its source location.\n\n")
        for entry in new_entries:
            f.write(entry + "\n")
    print(f"Found {len(new_entries)} new TODO(s) in {file_path}", file=sys.stderr)

print("{}")
